name = "skalora-crm-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "75bcda4af452221f9e0b085605e562ef"

[[d1_databases]]
binding = "DB"
database_name = "skalora-crm"
database_id = "866b28ed-f201-46f7-8312-b1aae9d40380"

[vars]
CRM_SECRET = "skalora2024"
